name: bmi_calculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  bloc_pattern: ^3.0.0
    

  cupertino_icons: ^1.0.4

  font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4  
    

flutter:
  uses-material-design: true
